# Generated by Django 2.1.5 on 2021-11-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('ID_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='aparatos',
            fields=[
                ('codigoA', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'aparatos',
                'verbose_name_plural': 'aparatos',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='clases',
            fields=[
                ('Codigo_clas', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateTimeField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'clases',
                'verbose_name_plural': 'clases',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='clases_socios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('Codigoclas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.clases')),
            ],
            options={
                'verbose_name': 'clases_socios',
                'verbose_name_plural': 'clases_socios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.IntegerField(max_length=20)),
                ('experiencia', models.CharField(max_length=200)),
                ('titulacion', models.CharField(max_length=150)),
                ('Codigo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.clases')),
            ],
        ),
        migrations.CreateModel(
            name='entrenador_tipoactividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('Dni_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.entrenador')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.actividad')),
            ],
            options={
                'verbose_name': 'entrenador_tipoactividad',
                'verbose_name_plural': 'entrenador_tipodeactividades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='salas',
            fields=[
                ('numeroS', models.AutoField(primary_key=True, serialize=False)),
                ('metros', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=120)),
                ('Codigo_clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.clases')),
                ('codigoA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.aparatos')),
            ],
            options={
                'verbose_name': 'salas',
                'verbose_name_plural': 'salas',
                'ordering': ['metros'],
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('DniS', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=200)),
                ('CBU', models.CharField(max_length=150)),
                ('direcciòn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='clases_socios',
            name='dni_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Socios'),
        ),
    ]
